# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: Install dotnet
  inputs:
    useGlobalJson: true
- script: dotnet build "Ejemplo.sln"
- script: dotnet test "Ejemplo.sln"
