trigger:
- main

strategy:
  matrix:
    Ubuntu:
      imageName: "ubuntu-latest"
    Windows:
      imageName: "windows-latest"
    Mac:
      imageName: "macos-latest"

pool:
  vmImage: $(imageName)

steps:
- checkout: self
- task: UseDotNet@2
  inputs:
    useGlobalJson: true
- script: dotnet build "Ejemplo.sln"
- script: dotnet test "Ejemplo.sln"
