name: Integration
on: [push]
jobs:
  build:
    strategy:
      matrix:
        agent: ["ubuntu-latest","windows-latest","macos-latest"]
    name: Integration job in ${{matrix.agent}}
    runs-on: ${{matrix.agent}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v4
      - run: dotnet build "Ejemplo.sln"
      - run: dotnet test "Ejemplo.sln"
